//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P_Login
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class ClienVisitBackUp
    {
        public int column1 { get; set; }
        public int column2 { get; set; }
        public int column3 { get; set; }
        public string column4 { get; set; }
        public System.DateTime column5 { get; set; }
        public string column6 { get; set; }
        public System.DateTime column7 { get; set; }
        public int column8 { get; set; }
        public double column9 { get; set; }
        public string column10 { get; set; }
        public string column11 { get; set; }
        public int column12 { get; set; }
        public double column13 { get; set; }
        public double column14 { get; set; }
        public System.DateTime column15 { get; set; }
        public string column16 { get; set; }
        public string column17 { get; set; }
        public string IDCode { get; set; }
        public int VisitIDCode { get; set; }
        public string TypeCode { get; set; }
        public string CareLevelCode { get; set; }
        public int ServiceGUID { get; set; }
        public int VisitTypeCareLevelGUID { get; set; }
        public string PatientName { get; set; }
        public string ProviderDisplayName { get; set; }
        public string column26 { get; set; }
        public int column27 { get; set; }
        public string column28 { get; set; }
        public int column29 { get; set; }
        public string column30 { get; set; }
        public string column31 { get; set; }
        public string column32 { get; set; }
        public string column33 { get; set; }
        public string column34 { get; set; }
        public string column35 { get; set; }
        public string column36 { get; set; }
        public string column37 { get; set; }
        public string column38 { get; set; }
        public int column39 { get; set; }
        public string column40 { get; set; }
        public string column41 { get; set; }
        public string column42 { get; set; }
    }
}
