//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P_Login
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class ClientVisit_OPD
    {
        public Nullable<long> ClientVisitGUID { get; set; }
        public long ClientGUID { get; set; }
        public Nullable<long> ChartGUID { get; set; }
        public string ClientDisplayName { get; set; }
        public Nullable<int> MRN { get; set; }
        public Nullable<int> VisitID { get; set; }
        public string CurrentLocation { get; set; }
        public string TypeCode { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<int> AGE { get; set; }
        public string Phone { get; set; }
        public string GenderCode { get; set; }
        public string Facility { get; set; }
        public Nullable<System.DateTime> AdmitDTM { get; set; }
    }
}
